name: New-Tab CI build

on:
    push:
        branches: [ "main", "1.x" ]  # Trigger on push to 'main' and '1.x' branches
    pull_request:
        branches: [ "main" ]          # Trigger on PR to 'main' branch

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [ 22.x ]  # Matrix for Node.js versions

        steps:
            -   uses: actions/checkout@v4  # Checkout the repository
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v4
                with:
                    node-version: ${{ matrix.node-version }}
                    cache: 'npm'  # Cache npm dependencies

            -   run: npm install   # Install dependencies
            -   run: npm run build --if-present  # Build the project if the 'build' script exists

            # Step 5: Create ZIP File
            -   name: Create ZIP File
                run: |
                    zip -r new-tab-${{ github.ref_name }}.zip ./dist  # Create zip of the 'dist' folder (make sure it's present)
                shell: bash

            # Step 7: Upload the ZIP file as a release asset
            -   name: Create GitHub Release and Upload Asset
                uses: softprops/action-gh-release@v2
                with:
                    if: startsWith(github.ref, 'refs/tags/')
                    token: ${{ secrets.GITHUB_TOKEN }}  # Use the default GITHUB_TOKEN to create the release
                    files: new-tab-${{ github.ref_name }}.zip  # Upload the ZIP file
