name: New-Tab CI build

on:
    push:
        tags:
            - "v*.*.*"
        branches: [ "main", "1.x" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout project code
                uses: actions/checkout@v4

            -   name: Use Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: 22
                    cache: 'npm'

            -   name: Install dependencies
                run: npm install

            -   name: Build application
                run: npm run build --if-present

            - name: Create GitHub release
              uses: softprops/action-gh-release@v2
              with:
                  files: dist/**
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
